<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>styl</string>
		<string>stylus</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>㎆ Stylus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mb</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(?:^[ ]+)?(//).*$</string>
			<key>name</key>
			<string>comment.line.mb</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)\&quot;</string>
			<key>end</key>
			<string>(?x)\&quot;</string>
			<key>name</key>
			<string>string.quoted.double.mb</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)\'</string>
			<key>end</key>
			<string>(?x)\'</string>
			<key>name</key>
			<string>string.quoted.single.mb</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.css</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(\#)[a-zA-Z][a-zA-Z0-9_-]*</string>
			<key>name</key>
			<string>entity.other.attribute-name.id.mb</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)(?:\b(\d+))|(\#[a-fA-F0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.stylus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)(!important|for|in|return|true|false|null|if|else|unless|return)</string>
			<key>name</key>
			<string>keyword.control.mb</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mb</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)([-a-zA-Z_][-\w]*)?(\()</string>
			<key>name</key>
			<string>meta.function.mb</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.mb</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(\.)[a-z]{1}[a-zA-Z0-9_-]*</string>
			<key>name</key>
			<string>entity.other.attribute-name.class.mb</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)(?&lt;=\s|^)(\*|span|input|textarea|body)(?=,|\s+\{|$)</string>
			<key>name</key>
			<string>entity.name.tag.mb</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.mb</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(:)(active|hover|link|visited|focus)</string>
			<key>name</key>
			<string>entity.other.attribute-name.pseudo-class.mb</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.stylus.mb</string>
	<key>uuid</key>
	<string>0FED80AB-EC09-4147-83AF-F8452F78FDE9</string>
</dict>
</plist>
