<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>styl</string>
		<string>stylus</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>㎆ Stylus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(?:^[ ]+)?(//).*$</string>
			<key>name</key>
			<string>comment.line.stylus</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)\&quot;</string>
			<key>end</key>
			<string>(?x)\&quot;</string>
			<key>name</key>
			<string>string.quoted.double.stylus</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)\'</string>
			<key>end</key>
			<string>(?x)\'</string>
			<key>name</key>
			<string>string.quoted.single.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(?&lt;=^|\s\s|,\s)
			(\#) [a-zA-Z] [a-zA-Z0-9_-]*
			</string>
			<key>name</key>
			<string>entity.other.attribute-name.id.stylus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)(?:\b(\d+(?:px)?))|(\#[a-fA-F0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.stylus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)\b(for|in|return|true|false|null|if|else|unless)\b</string>
			<key>name</key>
			<string>keyword.control.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)([-a-zA-Z_][-\w]*)?(\()</string>
			<key>name</key>
			<string>meta.function.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(\.)[a-z]{1}[a-zA-Z0-9_-]*</string>
			<key>name</key>
			<string>entity.other.attribute-name.class.stylus</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)(?&lt;=\s|^)(\*|div|span|input|textarea|body)(?=,|:|\s+\{|$)</string>
			<key>name</key>
			<string>entity.name.tag.stylus</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.stylus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(:)[-a-z]+\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.pseudo-selector.stylus</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.stylus</string>
	<key>uuid</key>
	<string>0FED80AB-EC09-4147-83AF-F8452F78FDE9</string>
</dict>
</plist>
